---
title: "DATA608_Final Project"
author: "LeTicia Cancel"
date: "5/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, error=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(shiny)
library(plotly)
library(stringr)
require(maps)
require(gridExtra)
library(tidyr)
```

```{r}
snap_person <- read.csv("https://raw.githubusercontent.com/ltcancel/DATA608/main/Final%20Project/SNAP%20Person%20Count%2005032022_cleaned.csv")
snap_hh <- read.csv("https://raw.githubusercontent.com/ltcancel/DATA608/main/Final%20Project/SNAP%20Household%20Count%2005032022_cleaned.csv")
survey_df <- read.csv("https://raw.githubusercontent.com/ltcancel/DATA608/main/Final%20Project/Food%20Security%20Survey.csv")
head(snap_person)
head(snap_hh)
head(survey_df)
```

```{r fig.height=30, fig.width=30, warning=FALSE}
# clean the February column of both dataframes toreplace '--' with NA and convert to an integer
snap_hh$February <- as.integer(gsub(",","",snap_hh$February))
snap_person$February <- as.integer(gsub(",","",snap_person$February))
snap_hh$State <- tolower(snap_hh$State)
snap_person$State <- tolower(snap_person$State)
survey_df <- select(survey_df, -c(US1, US2, US3, US4, US5))
head(snap_person)
head(snap_hh)
head(survey_df)
```

```{r}
#combine map data from the Maps library which includes longitude and latitude data
states_map <- map_data("state")
snap_hh_map <- merge(snap_hh, states_map, by.x = c("State"), by.y = c("region"))
snap_person_map <- merge(snap_person, states_map, by.x = c("State"), by.y = c("region"))
head(snap_hh_map)
head(snap_person_map)
```

```{r}
plot_hh1 <- ggplot(snap_hh_map, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = February), color = "white") +
  scale_fill_viridis_c(option = "C")

plot_hh2 <- ggplot(snap_hh, aes(x = reorder(State, February), y = February, fill = State)) +
  geom_bar(stat = "identity") +
  labs(x = "State", y = "Household Count", title = "Supplemental Nutrition Assistance Program: Number of Households Participating") +
  coord_flip() +
  theme(legend.position = "none")
```


```{r fig.height=7, fig.width=20, warning=FALSE}
grid.arrange(plot_hh1, plot_hh2, ncol=2)
```


```{r fig.height=7, fig.width=20, warning=FALSE}
plot_person1 <- ggplot(snap_person_map, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = February), color = "white") +
  scale_fill_viridis_c(option = "C")

plot_person2 <- ggplot(snap_person, aes(x = reorder(State, February), y = February, fill = State)) +
  geom_bar(stat = "identity") +
  labs(x = "State", y = "Person Count", title = "Supplemental Nutrition Assistance Program: Number of Persons Participating") +
  coord_flip() +
  theme(legend.position = "none")

grid.arrange(plot_person1, plot_person2, ncol=2)
```

Questions
1) Enough of the kinds of food wanted
2) Enough food, but not always the kinds wanted
3) Sometimes not enough to eat
4) Often not enough to eat
5) Did not report


```{r}
transformed_df <- survey_df %>%
  gather(key = "response", value = "count", AL1:METRO5)

transformed_df$State <- substr(transformed_df$response, 1,2)
transformed_df$response <- substr(transformed_df$response, 3, 3)

transformed_df <- transformed_df %>%
  mutate(response = ifelse(response =="1", "Enough of the kinds of food wanted", ifelse(response=="2", "Enough food, but not always the kinds wanted", ifelse(response=="3", "Sometimes not enough to eat", ifelse(response=="4", "Often not enough to eat", ifelse(response=="5","Did not report",NA))))))

head(transformed_df)
```



```{r}
ggplot(transformed_df, aes(fill = response, x = State, y = count)) +
  geom_bar(position = "dodge", stat = "identity") +
  facet_wrap(~Characteristics)
```

```{r fig.height=20, fig.width=20}
age_df <- transformed_df %>%
  filter(Question == "Confidence in paying next rent or mortgage") 

ggplot(age_df, aes(fill = response, x = State, y = count)) +
  geom_bar(position = "dodge", stat = "identity")
```

```{r}
ui <- fluidPage(
  
  headerPanel("2010 Cause of Death by State"),
  
  sidebarPanel(
   selectInput('cause','Cause of Death', unique(transformed_df$Question)) 
  ),
  
  mainPanel(plotlyOutput("plot1"))
)
server <- function(input,output){
  
  output$plot1 <- renderPlotly({
      
  filterdf <- transformed_df %>% 
    filter(Question == input$cause)
  
  plot_ly(filterdf, x = ~State, y = ~count, type = "bar")
  
  })
  
}

shinyApp(ui, server)
```

Resources:
Number of persons participating in Supplemental Nutrition Assistance program (SNAP) as of May 3, 2022
Number of households participating in Supplemental Nutrition Assistance program (SNAP) as of May 3, 2022



